### ISSUE TITLE
WhatsApp 2.2419.11.0 It does not work

### ISSUE THREAD

**Issue by MrX0r** [d-roduit/WhatsAppSpy#35]
Hello
WhatsAppSpy does not work with the latest WhatsApp Desktop version of MS Stroe 2.2419.11.0

Number of connections and Last connection are not displayed even though I tried with 2 phones and other friends were online.

Please fix it, thank you very much

Info: Windows 10 x64
npm install ran without problems, that's not the reason

**Comment by d-roduit** [comment]
Hey,

Thanks for opening an issue and already providing details about the OS and version of WhatsApp.

I'll have more time in about 5 days to look into the problem. I'll look at what might be wrong at that time 👍

**Comment by d-roduit** [comment]
Hello @MrX0r,

Yes, I tested on Windows 10 with the latest version of WhatsApp Desktop (`2.2421.7.0`) in the MS Store. I didn't find any problem in the application itself. On the other hand, WhatsApp seems to have changed the way it manages status.

When I developed WhatsAppSpy, the contact's status always remained displayed if the contact had not decided to hide it. And the status was updated visually as soon as there was a change in status. Also, the name of the contact being spied on always remained in the same place, even when the status changed or disappeared. Looks like WhatsApp has also changed that.

Now the status no longer seems to always remain displayed. It automatically disappears after a certain time, even when the contact has not decided to hide it when not online. After it disappears, the status is no longer updated visually when changes occur. To view the contact's status again, you must interact with the application, such as clicking in the discussion for example. Finally, when the status disappears, the contact name moves slightly downward to center vertically with the contact image, and this was not happening before.

Despite these changes, WhatsAppSpy still correctly recognizes status changes when the status is displayed, provided you have configured the settings correctly. When I did the tests, and with the dark theme of WhatsApp, I just needed to change the values ​​for the screenshot parameters. I left the other values ​​at default and it worked straight away. For the light WhatsApp theme, I had to also change the value of the parameter for the color to be identified so as not to have false positives.

Are you sure you have correctly configured the settings for the screenshot, and if necessary for the color to be identified ?
And if so, are the status messages that are logged in the log area on the main page of the application correct in relation to the contact's status appearing in WhatsApp ?

I realize that the current functioning of the application should be reviewed, because it becomes useless after the status disappears. Something should be done about that. And maybe your problem is linked to this situation ?! But in the case where the status is displayed, I haven't found any bug.
